### ISSUE TITLE
Weewx stop itself after a while

### ISSUE THREAD

**Issue by metalheadz** [matthewwall/weewx-sdr#110]
Hi!

My weewx service just stop itself after some time and I activated debug to find the last thing executed. 

Here was the log :

Jan 26 21:27:02 weewx weewx[12311] DEBUG user.sdr: lines=[]
Jan 26 21:27:05 weewx weewx[12311] DEBUG user.sdr: lines=[]
Jan 26 21:27:08 weewx weewx[12311] DEBUG user.sdr: lines=[]
Jan 26 21:27:11 weewx weewx[12311] DEBUG user.sdr: lines=[]
Jan 26 21:27:16 weewx weewx[12311] DEBUG user.sdr: lines=['{"time" : "2021-01-27 02:27:14", "model" : "Acurite-5n1", "message_type" : 56, "id" : 3677, "channel" : "A", "sequence_num" : 0, "battery_ok" : 1, "wind_avg_km_h" : 0.000, "temperature_F" : 19.000, "humidity" : 84, "mic" : "CHECKSUM"}\n', '{"time" : "2021-01-27 02:27:14", "model" : "Acurite-5n1", "message_type" : 56, "id" : 3677, "channel" : "A", "sequence_num" : 1, "battery_ok" : 1, "wind_avg_km_h" : 0.000, "temperature_F" : 19.000, "humidity" : 84, "mic" : "CHECKSUM"}\n', '{"time" : "2021-01-27 02:27:14", "model" : "Acurite-5n1", "message_type" : 56, "id" : 3677, "channel" : "A", "sequence_num" : 2, "battery_ok" : 1, "wind_avg_km_h" : 0.000, "temperature_F" : 19.000, "humidity" : 84, "mic" : "CHECKSUM"}\n', '']
Jan 26 21:27:17 weewx weewx[12311] DEBUG user.sdr: packet={'windSpeed': 0.0, 'outTemp': 19.0, 'outHumidity': 84.0, 'dateTime': 1611714434, 'usUnits': 1}
Jan 26 21:27:20 weewx weewx[12311] DEBUG user.sdr: packet={'windSpeed': 0.0, 'outTemp': 19.0, 'outHumidity': 84.0, 'dateTime': 1611714434, 'usUnits': 1}
Jan 26 21:27:24 weewx weewx[12311] DEBUG user.sdr: packet={'windSpeed': 0.0, 'outTemp': 19.0, 'outHumidity': 84.0, 'dateTime': 1611714434, 'usUnits': 1}
Jan 26 21:27:30 weewx weewx[12311] DEBUG user.sdr: parse_text failed: ts=None payload=None line=

Looks like the parse failed make the main script exit and no data is retrieved until I restart everything.

have an idea how to fix this?

**Comment by matthewwall** [comment]
subprocess handling was fixed some time ago
