### ISSUE TITLE
La Crosse LTV-R3 rain sensor

### ISSUE THREAD

**Issue by srhuston** [matthewwall/weewx-sdr#145]
The LTV-R3 rain sensor comes with the V61 kit which includes a BreezePro sensor (WSDTH04).  The BreezePro is already parsed properly, but I found the R3 is just ignored.  rtl_433 sees the data (I experimented with that before finding weewx-sdr) so I think it's a simple matter of parsing, I just don't know enough about how all this works to try my hand at it yet.

out: [u'{"time" : "2022-01-16 04:43:25", "model" : "LaCrosse-R3", "id" : 7417878, "battery_ok" : 1, "seq" : 1, "rain_mm" : 10921.750, "rain2_mm" : 10921.750, "mic" : "CRC"}
\n']

I tried running the command with "--hide parsed,out,empty" but it didn't show anything as unparsed, again I'm guessing I don't understand enough about this yet to be helpful.

**Comment by matthewwall** [comment]
added to sdr.py at commit 885d5b6
