### ISSUE TITLE
Acurite 06045 Lighting detector

### ISSUE THREAD

**Issue by RedVox73** [matthewwall/weewx-sdr#146]
I currently am trying to use the Acurite 06045 lightning detector but run into 2 problems. (1 might be weewx related)

- The sensor is being received however every pack is shown 3 times.
- In Weewx the strikes total of every data pack is being added to the total instead of the difference between the data packs. ( the sensor sens out the total, like a rain sensor) (The sensor temp and humidity are mapped to "inTemp and inHumidity and work fine)

![image](https://user-images.githubusercontent.com/99034896/154833121-3e9da2e9-7222-427b-8a99-9ddd0ddf2cf0.png)

Any advise on where / how to fix these items?

**Comment by andylittle** [comment]
https://groups.google.com/g/weewx-user/c/NQIQ6KhG7To?pli=1

**Comment by andylittle** [comment]
https://github.com/matthewwall/weewx-sdr/issues/57
