### ISSUE TITLE
TFA pluviometer 30.3233.01 not parsed

### ISSUE THREAD

**Issue by modussiam** [matthewwall/weewx-sdr#156]
Hello,
I'd like to use a [TFA pluviometer sensor ( ref : 30.3233.01 )](https://www.tfa-dostmann.de/en/product/rain-transmitter-30-3233/) with weewx-sdr  .
It is recognized by sdr_433 :

**time      : 2022-06-18 13:51:04
model     : TFA-Drop     id        : a9f99
Battery   : 1            Rain in MM: 32.512        Integrity : CHECKSUM**

But the output in the weewx-sdr driver is not parsed .                
**out: ['{"time" : "2022-06-18 07:04:34", "model" : "TFA-Drop", "id" : 696217, "battery_ok" : 1, "rain_mm" : 29.210, "mic" : "CHECKSUM"}\n']**

i'm not a coder and don't know how to write the parser .
All help will be appreciated .
Thank you and have a nice wwek !

**Comment by modussiam** [comment]
hello Andy,
It works !
**parsed: {'dateTime': 1655731747, 'usUnits': 16, 'rain_total.0000.TFADropPacket': 1.016, 'battery.0000.TFADropPacket': 1}**
A big THANK YOU !
Sheers from france !
Bye !

**Comment by andylittle** [comment]
Check to make sure the rain amount is correct in weewx.

**Comment by modussiam** [comment]
Hey,
rtl_433 gives 10 millimeter  and weewx gives 10 centimeters   
the amount in weewx is 10 X the amount in rtl_433

**Comment by modussiam** [comment]
I've modified weewx.conf to have rain amount in millimeters but it's allways exactly 10 X higher compared with rtl_433 .

**Comment by andylittle** [comment]
change line 3117 to pkt['usUnits'] = weewx.METRICWX or grab [this.](https://github.com/andylittle/weewx-sdr-1/commit/c7d2e47138e67c42cb7571615ce70cd347d40280)

**Comment by matthewwall** [comment]
thank you both!  this has been incorporated into weewx-sdr
