### ISSUE TITLE
problems with configuration on Dietpi

### ISSUE THREAD

**Issue by pcossu61** [matthewwall/weewx-sdr#168]
I try to install weewx-sdr on Dietpi on a Pine64
following the instructions
I get an error
dietpi@DietPiBusterweewx:/usr/share/weewx$ sudo PYTHONPATH=bin python /usr/share/weewx/user/sdr.py --cmd="rtl_433 -f 868.3M -s 1024k -M utc -F json"
sudo: unable to resolve host DietPiBusterweewx: Name or service not known
Traceback (most recent call last):
  File "/usr/share/weewx/user/sdr.py", line 106, in <module>
    import weewx.drivers
ImportError: No module named weewx.drivers

**Comment by matthewwall** [comment]
with a current directory of `/usr/share/weewx`, the invocation should have been:
```
sudo PYTHONPATH=. python /usr/share/weewx/user/sdr.py --cmd="rtl_433 -f 868.3M -s 1024k -M utc -F json"
```
alternatively, using an absolute path will work anywhere:
```
sudo PYTHONPATH=/usr/share/weewx python /usr/share/weewx/user/sdr.py --cmd="rtl_433 -f 868.3M -s 1024k -M utc -F json"
```
