### ISSUE TITLE
Incorrect delta for lightning strike

### ISSUE THREAD

**Issue by mfraser** [matthewwall/weewx-sdr#178]
The default delta for lightning strikes is
DEFAULT_DELTAS = {
'rain': 'rain_total',
'strikes': 'strikes_total'}

When it should be 'lightning_strike_count': 'strikes_total'

After changing the delta over to lightning_strike_count I see a graph for lightning strikes.

**Comment by matthewwall** [comment]
fixed at commit 7925939
