### ISSUE TITLE
Add support for LaCrosse TX4U (temp/humidity) sensor.

### ISSUE THREAD

**Issue by kk6fut** [matthewwall/weewx-sdr#18]
Request to incorporate support for the LaCrosse TX4U temperature/humidity sensor into your mainline code branch...

Code attached for sdr.py which adds this support. Happy to figure out how to pull/commit the code directly:

class LaCrosseTXPacket(Packet):

    # {"time" : "2017-07-30 21:11:19", "model" : "LaCrosse TX Sensor", "id" : 127, "humidity" : 34.000}\n', '{"time" : "2017-07-30 21:11:19", "model" : "LaCrosse TX Sensor", "id" : 127, "humidity" : 34.000}\n', '{"time" : "2017-07-30 21:11:19", "model" : "LaCrosse TX Sensor", "id" : 127, "temperature_C" : 27.100}\n', '{"time" : "2017-07-30 21:11:19", "model" : "LaCrosse TX Sensor", "id" : 127, "temperature_C" : 27.100}

    IDENTIFIER = "LaCrosse TX Sensor"

    @staticmethod
    def parse_json(obj):
        pkt = dict()
        pkt['dateTime'] = Packet.parse_time(obj.get('time'))
        pkt['usUnits'] = weewx.METRIC
        sensor_id = obj.get('id')
        pkt['temperature'] = Packet.get_float(obj, 'temperature_C')
        pkt['humidity'] = Packet.get_float(obj, 'humidity')
        pkt = Packet.add_identifiers(pkt, sensor_id, LaCrosseTXPacket.__name__)
        return pkt

**Comment by matthewwall** [comment]
added at commit abe616c

thank you!
