### ISSUE TITLE
Battery status on Oregon Scientific sensors doesn't work

### ISSUE THREAD

**Issue by chaoschris** [matthewwall/weewx-sdr#190]
Battery status on Oregon Scientific sensors doesn't work.

weewx.conf:

[[sensor_map]]
        outTemp = temperature.1:95.OSTHGR968Packet
        outHumidity = humidity.1:95.OSTHGR968Packet
        outTempBatteryStatus = battery.1:95.OSTHGR968Packet
        inTemp = temperature.0:236.OSBTHR968Packet
        inHumidity = humidity.0:236.OSBTHR968Packet
        pressure = pressure.0:236.OSBTHR968Packet
        inTempBatteryStatus = battery.0:236.OSBTHR968Packet
        extraTemp1 = temperature.2:148.OSTHGR122NPacket
        extraHumidity1 = humidity.2:148.OSTHGR122NPacket

real data collected from SDR:

{"time" : "2024-08-05 14:51:51", "model" : "Oregon-THGR968", "id" : 95, "channel" : 1, "battery_ok" : 1, "temperature_C" : 25.800, "humidity" : 48}
{"time" : "2024-08-05 14:51:51", "model" : "Oregon-THGR968", "id" : 95, "channel" : 1, "battery_ok" : 1, "temperature_C" : 25.800, "humidity" : 48}
{"time" : "2024-08-05 14:52:15", "model" : "Oregon-BHTR968", "id" : 236, "channel" : 0, "battery_ok" : 1, "temperature_C" : 22.700, "humidity" : 62, "pressure_hPa" : 995.000}
{"time" : "2024-08-05 14:52:15", "model" : "Oregon-BHTR968", "id" : 236, "channel" : 0, "battery_ok" : 1, "temperature_C" : 22.700, "humidity" : 62, "pressure_hPa" : 995.000}
{"time" : "2024-08-05 14:52:28", "model" : "Oregon-THGR968", "id" : 95, "channel" : 1, "battery_ok" : 1, "temperature_C" : 25.800, "humidity" : 48}
{"time" : "2024-08-05 14:52:28", "model" : "Oregon-THGR968", "id" : 95, "channel" : 1, "battery_ok" : 1, "temperature_C" : 25.800, "humidity" : 48}

the parser in sdr.py searches for a string "battery" and not for "battery_ok".
Is this right?

I have already tested some changes in the sdr.py, but didn' t got it working. 
The generated battery status on the web pages always shows "LOW" which isn't right.

**Comment by matthewwall** [comment]
fixed at commit b2dc2a0
