### ISSUE TITLE
sudo PYTHONPATH=bin python bin/user/sdr.py

### ISSUE THREAD

**Issue by taconugget** [matthewwall/weewx-sdr#2]
Im trying to install w/ weewx but when following the realm it has me do this:
sudo PYTHONPATH=bin python bin/user/sdr.py

I get the following error:
Traceback (most recent call last):
  File "bin/user/sdr.py", line 699, in <module>
    [--path=PATH] [--ld_library_path=LD_LIBRARY_PATH]""" % DEFAULT_CMD
ValueError: unsupported format character 'p' (0x70) at index 1

Im relatively new to this and can't figure out where to go from here...
Any help would be appreciated.
Thanks,
Brad

**Comment by matthewwall** [comment]
fixed at commit cc7984db6a8ec660c9a4fb6529e58ebe7bdc96c3
