### ISSUE TITLE
Indent problem

### ISSUE THREAD

**Issue by captain-coredump** [matthewwall/weewx-sdr#20]
Seems like there is an extra tab at the beginning of the line. Version 0.32, line 1475:

Aug  9 09:12:48 WXpi3 weewx[7950]:     ****    File "/usr/share/weewx/user/sdr.py", line 1475
Aug  9 09:12:48 WXpi3 weewx[7950]:     ****      pkt['pressure'] = Packet.get_float(obj, 'pressure_hPa')
Aug  9 09:12:48 WXpi3 weewx[7950]:     ****      ^
Aug  9 09:12:48 WXpi3 weewx[7950]:     ****  IndentationError: unexpected indent
Aug  9 09:12:48 WXpi3 weewx[7950]:     ****  Exiting.

I removed the tab on my installed file, and it appears to be working (with a caveat that I don't use that device on my WX station).....

**Comment by matthewwall** [comment]
fixed at commit f50b82b

sorry about that - i guess i need to check pull requests a bit more closely
