### ISSUE TITLE
Parser for WH450 sensor

### ISSUE THREAD

**Issue by magazaki** [matthewwall/weewx-sdr#22]
When manually running sudo PYTHONPATH=/usr/share/weewx python /usr/share/weewx/user/sdr.py --cmd="rtl_433 -q -U -F json -G"

I receive the following:
out: ['AcuRite Rain Gauge Total Rain is 1350.5mm\n', 'Raw Message: 34 4a 8d 00 00\n', '{"time" : "2017-09-14 20:24:43", "model" : "WT450 sensor", "id" : 1, "channel" : 2, "battery" : "OK", "temperature_C" : 25.090, "humidity" : 49}\n', '{"time" : "2017-09-14 20:24:44", "model" : "WT450 sensor", "id" : 1, "channel" : 2, "battery" : "OK", "temperature_C" : 25.110, "humidity" : 49}\n', '{"time" : "2017-09-14 20:24:44", "model" : "WT450 sensor", "id" : 1, "channel" : 2, "battery" : "OK", "temperature_C" : 25.120, "humidity" : 49}\n']

When running the weewx service I see "parse_json: unknown model WT450 sensor" in my syslog on my Rpi.

I think I need a parser, anyone ?:)

brg
Magnus
/Noob

**Comment by matthewwall** [comment]
support for wt450 sensor added at version 0.34 commit b2913ef
