### ISSUE TITLE
acurite 986 now using JSON/structured data.

### ISSUE THREAD

**Issue by rct** [matthewwall/weewx-sdr#27]
On 2018-04-23, the Acurite 986 fridge/freezer decoder in rtl_433 was changed to use structured data.  Ref: merbanan/rtl_433#709.  

Battery status was added.  Also reception reliability may be slightly improved due to a workaround for the missing last bit.  The decoder is now enabled by default.

New output:
```
{"time" : "2018-04-22 18:01:03", "model" : "Acurite 986 Sensor", "id" : 43248, "channel" : "1R", "temperature_F" : 69, "battery" : "OK", "status" : 0}
```

**Comment by matthewwall** [comment]
support for json added in weewx-sdr v0.41

thank you for the sample output!
