### ISSUE TITLE
timed out waiting for stderr-thread

### ISSUE THREAD

**Issue by dbrb2** [matthewwall/weewx-sdr#32]
Approximately once every 2-3 days, weewx dies on me with the following: 

Oct 10 09:18:51 nas weewx[30868]: restx: WOW: Failed to publish record 2018-10-10 09:18:00 BST (1539159480): Failed upload after 3 tries
Oct 10 09:18:51 nas weewx[30868]: sdr: MainThread: shutdown process rtl_433 -q -U -F json
Oct 10 09:19:06 nas weewx[30868]: sdr: MainThread: timed out waiting for stderr-thread
Oct 10 09:19:06 nas weewx[30868]: engine: Caught unrecoverable exception in engine:
Oct 10 09:19:06 nas weewx[30868]:     ****  'int' object has no attribute 'upper'
Oct 10 09:19:06 nas weewx[30868]:     ****  Traceback (most recent call last):
Oct 10 09:19:06 nas weewx[30868]:     ****    File "/home/weewx/bin/weewx/engine.py", line 859, in main
Oct 10 09:19:06 nas weewx[30868]:     ****      engine.run()
Oct 10 09:19:06 nas weewx[30868]:     ****    File "/home/weewx/bin/weewx/engine.py", line 182, in run
Oct 10 09:19:06 nas weewx[30868]:     ****      for packet in self.console.genLoopPackets():
Oct 10 09:19:06 nas weewx[30868]:     ****    File "/home/weewx/bin/user/sdr.py", line 1921, in genLoopPackets
Oct 10 09:19:06 nas weewx[30868]:     ****      for packet in PacketFactory.create(lines):
Oct 10 09:19:06 nas weewx[30868]:     ****    File "/home/weewx/bin/user/sdr.py", line 1792, in create
Oct 10 09:19:06 nas weewx[30868]:     ****      pkt = PacketFactory.parse_json(lines)
Oct 10 09:19:06 nas weewx[30868]:     ****    File "/home/weewx/bin/user/sdr.py", line 1808, in parse_json
Oct 10 09:19:06 nas weewx[30868]:     ****      return parser.parse_json(obj)
Oct 10 09:19:06 nas weewx[30868]:     ****    File "/home/weewx/bin/user/sdr.py", line 575, in parse_json
Oct 10 09:19:06 nas weewx[30868]:     ****      return Acurite.insert_ids(pkt, Acurite986Packet.__name__)
Oct 10 09:19:06 nas weewx[30868]:     ****    File "/home/weewx/bin/user/sdr.py", line 330, in insert_ids
Oct 10 09:19:06 nas weewx[30868]:     ****      sensor_id = pkt.pop('hardware_id', '0000').upper()
Oct 10 09:19:06 nas weewx[30868]:     ****  AttributeError: 'int' object has no attribute 'upper'
Oct 10 09:19:06 nas weewx[30868]:     ****  Exiting.

**Comment by matthewwall** [comment]
fixed at commit 7ee1208.  thank you for reporting this - it is rather obscure.
