### ISSUE TITLE
Bresser 5in-1 Parser

### ISSUE THREAD

**Issue by mercurystorm** [matthewwall/weewx-sdr#35]
Battling to get a parser for my Bresser 5in1 weather station working

`class Bresser5in1(Packet):
#  'time' => '2018-12-15 16:04:04',
#  'model' => 'Bresser-5in1',
#  'id' => 118,
#  'temperature_C' => 6.4000000000000003552713678800500929355621337890625,
#  'humidity' => 87,
#  'wind_gust' => 2.79999999999999982236431605997495353221893310546875,
#  'wind_speed' => 2.899999999999999911182158029987476766109466552734375,
#  'wind_dir_deg' => 315,
#  'rain_mm' => 10.800000000000000710542735760100185871124267578125,
#  'data' => 'e7897fd71fd6ef9bff78f7feff18768028e02910640087080100',
#  'mic' => 'CHECKSUM',

# ’{“time" : "2018-12-15 16:04:04", "model" : "Bresser-5in1", "id" : 118, "temperature_C" : 6.400, "humidity" : 87, "wind_gust" : 2.800, "wind_speed" : 2.900, "wind_dir_deg" : 315.000, "rain_mm" : 10.800, "data" : "e7897fd71fd6ef9bff78f7feff18768028e02910640087080100", "mic" : "CHECKSUM"}#012'
    
IDENTIFIER = "Bresser-5in1"

    @staticmethod
    def parse_json(obj):
        pkt = dict()
        pkt['dateTime'] = Packet.parse_time(obj.get('time'))
        pkt['usUnits'] = weewx.METRICWX
        pkt['station_id'] = obj.get('id')
        pkt['temperature'] = Packet.get_float(obj, 'temperature_C')
        pkt['humidity'] = Packet.get_float(obj, 'humidity')
        pkt['wind_gust'] = Packet.get_float(obj, 'gust_speed_ms') 
        pkt['wind_speed'] = Packet.get_float(obj, 'wind_speed_ms')  
        pkt['wind_dir'] = Packet.get_float(obj, 'wind_dir_deg')
        pkt['rain_total'] = Packet.get_float(obj, 'rainfall_mm')
        pkt['uv'] = Packet.get_float(obj, 'uv')
        pkt['uv_index'] = Packet.get_float(obj, 'uvi')
        return Bresser5in1Packet.insert_ids(pkt)

    @staticmethod
    def insert_ids(pkt):
        station_id = pkt.pop('station_id', '0000')
        pkt = Packet.add_identifiers(pkt, station_id, Bresser5in1Packet.__name__)
        return pkt`

But it just returns errors:

Dec 15 17:21:56 raspberrypi weewx[13906]: sdr: MainThread: lines=['{"time" : "2018-12-15 17:21:52", "model" : "Bresser-5in1", "id" : 118, "temperature_C" : 6.300, "humidity" : 89, "wind_gust" : 2.400, "wind_speed" : 2.400, "wind_dir_deg" : 292.500, "rain_mm" : 11.200, "data" : "e5897fe12fdbef9cff76edfeff1a76801ed02410630089120100", "mic" : "CHECKSUM"}\n']
Dec 15 17:21:56 raspberrypi weewx[13906]: sdr: MainThread: parse_json: unknown model Bresser-5in1
Dec 15 17:21:56 raspberrypi weewx[13906]: sdr: MainThread: punt unrecognized line '{"time" : "2018-12-15 17:21:52", "model" : "Bresser-5in1", "id" : 118, "temperature_C" : 6.300, "humidity" : 89, "wind_gust" : 2.400, "wind_speed" : 2.400, "wind_dir_deg" : 292.500, "rain_mm" : 11.200, "data" : "e5897fe12fdbef9cff76edfeff1a76801ed02410630089120100", "mic" : "CHECKSUM"}#012'
Dec 15 17:21:59 raspberrypi weewx[13906]: sdr: MainThread: lines=[]
Dec 15 17:22:02 raspberrypi weewx[13906]: sdr: MainThread: lines=[]
Dec 15 17:22:05 raspberrypi weewx[13906]: sdr: MainThread: lines=[]
Dec 15 17:22:08 raspberrypi weewx[13906]: sdr: MainThread: lines=['{"time" : "2018-12-15 17:22:04", "model" : "Bresser-5in1", "id" : 118, "temperature_C" : 6.100, "humidity" : 89, "wind_gust" : 2.800, "wind_speed" : 2.200, "wind_dir_deg" : 22.500, "rain_mm" : 11.200, "data" : "ea897fd7efddef9eff76edfeff15768028102210610089120100", "mic" : "CHECKSUM"}\n']
Dec 15 17:22:08 raspberrypi weewx[13906]: sdr: MainThread: parse_json: unknown model Bresser-5in1
Dec 15 17:22:08 raspberrypi weewx[13906]: sdr: MainThread: punt unrecognized line '{"time" : "2018-12-15 17:22:04", "model" : "Bresser-5in1", "id" : 118, "temperature_C" : 6.100, "humidity" : 89, "wind_gust" : 2.800, "wind_speed" : 2.200, "wind_dir_deg" : 22.500, "rain_mm" : 11.200, "data" : "ea897fd7efddef9eff76edfeff15768028102210610089120100", "mic" : "CHECKSUM"}#012'
Dec 15 17:22:11 raspberrypi weewx[13906]: sdr: MainThread: lines=[]
Dec 15 17:22:14 raspberrypi weewx[13906]: sdr: MainThread: lines=[]
Dec 15 17:22:19 raspberrypi weewx[13906]: sdr: MainThread: lines=['{"time" : "2018-12-15 17:22:16", "model" : "Bresser-5in1", "id" : 118, "temperature_C" : 6.200, "humidity" : 88, "wind_gust" : 2.800, "wind_speed" : 2.500, "wind_dir_deg" : 337.500, "rain_mm" : 11.200, "data" : "e7897fd70fdaef9dff77edfeff18768028f02510620088120100", "mic" : "CHECKSUM"}\n']

**Comment by mercurystorm** [comment]
Got it working! :)

**Comment by matthewwall** [comment]
what is a 'Bresser 5n1'?

**Comment by mercurystorm** [comment]
> what is a 'Bresser 5n1'? i have never seen that hardware before.

https://www.bresser.de/en/Weather-Time/Weather-Stations/BRESSER-5-in-1-Professional-Weather-Center-with-256-Colour-Display.html

**Comment by Rossano95** [comment]
Hello, sorry if this is not the place to ask. I am trying to use weewx with a bresser 6in1. But I don't know how to configure weewx-sdr. I installed everything but I don't know how to select my sensors. 
This is the station: https://www.bresser.de/en/Weather-Time/Weather-Stations/BRESSER-Professional-WIFI-Weather-Centre-6in1.html

**Comment by andylittle** [comment]
https://groups.google.com/forum/#!forum/weewx-user is where support items go.

**Comment by Rossano95** [comment]
Hello again, I asked where you sended me but I think that the only persons that can help me are you here.
