### ISSUE TITLE
Alecto V1 Rain sensor not parsed

### ISSUE THREAD

**Issue by roberto1984** [matthewwall/weewx-sdr#39]
Hi Matthew,

as per the Alecto V1 Wind sensor,also the rain sensor is not parsed.
Below the output of the sdr.py driver

out: ['{"time" : "2019-01-20 15:29:21", "model" : "AlectoV1 Rain Sensor", "id" : 13, "channel" : 0, "battery" : "OK", "rain_total" : 15.500, "mic" : "CHECKSUM"}\n']

Please consider that the rain_total is the amount of the rain starting from the replacement of the battery.

If you wan to add the parser it will be very appreciated!

Thanks again!

**Comment by matthewwall** [comment]
support added at commit 68c0664

weewx-sdr v0.53
