### ISSUE TITLE
Calibeur RF-104

### ISSUE THREAD

**Issue by labando** [matthewwall/weewx-sdr#4]
Hi
Could you please add support for Calibeur RF-104?

Data look like this:
out: ['2016-11-01 01:25:28 :\tCalibeur RF-104\n', '\tID:\t 1\n', '\tTemperature:\t 1.8 C\n', '\tHumidity:\t 71 %\n']

Thanks!

**Comment by matthewwall** [comment]
done at commit 1debbc3
