### ISSUE TITLE
WEATER STATION WS1041

### ISSUE THREAD

**Issue by wifi75** [matthewwall/weewx-sdr#41]
Hello,
unfortunately I can not find any sensor for my ws-1041.
is there any other way?

**Comment by matthewwall** [comment]
start by running rtl_433 directly.  if you do not see the signals from your sensors, then you need to work with the rtl_433 developers to add support for your sensors to rtl_433.

as soon as rtl_433 can output the data from your sensors, come back here with the output and we will add that support to weewx-sdr.
