### ISSUE TITLE
WH1080 ID changes after restart

### ISSUE THREAD

**Issue by willie42** [matthewwall/weewx-sdr#42]
I have issues with my weather-station. So I have to restart it from time to time. After resetting it, it starts sending with a new ID and so I have to run the driver directly to get the ID and to edit the weewx.conf.
Is there any possibility to set a wildcard? Like so:
rain_total = rain_total.*.FOWH1080Packet

Regards, Willie

**Comment by matthewwall** [comment]
yes.  glob pattern matches are supported.

**Comment by willie42** [comment]
It is that simple - I just should have tried it :)
I changed the lines as described and it works.
Thanks a lot.
