### ISSUE TITLE
FOWHx report rain is in cm not in mm

### ISSUE THREAD

**Issue by tixel1** [matthewwall/weewx-sdr#58]
This packet report 10x the fallen rain. the station gives the rain in mm and the driver in cm.

**Comment by matthewwall** [comment]
could you confirm which type of FOWH packet you are using?

there are 10 different kinds of FOWH packets in sdr right now.  these have rain: FOWH1080, FOWHx080, FOWH3080, FOWH24, FOWH65B

**Comment by matthewwall** [comment]
fixed at commit 662ad60 for 1080/3080 packets
