### ISSUE TITLE
Acurite 899 Rain gauge not parsed

### ISSUE THREAD

**Issue by rknobbe** [matthewwall/weewx-sdr#69]
[acurite-rain899.txt](https://github.com/matthewwall/weewx-sdr/files/3932949/acurite-rain899.txt)

I have a patch for sdr.py to add Acurite Rain899 parsing to sdr.py

**Comment by matthewwall** [comment]
added at commit dd35822

**Comment by rknobbe** [comment]
Hold off on using this.  Data must be getting misinterpreted because it hasn't rained for days but the sensor is still reporting rain_mm valued in every sample.  This may be a problem with rtl_433.

`out:[u'{"time" : "2019-12-13 13:43:08", "model" : "Acurite-Rain899", "id" : 1699, "channel" : 0, "battery_ok" : 0, "rain_mm" : 6.096}\n', u'{"time" : "2019-12-13 13:43:08", "model" : "Acurite-Rain899", "id" : 1699, "channel" : 0, "battery_ok" : 0, "rain_mm" : 6.096}\n', u'{"time" : "2019-12-13 13:43:08", "model" : "Acurite-Rain899", "id" : 1699, "channel" : 0, "battery_ok" : 0, "rain_mm" : 6.096}\n']
`
![dayrain](https://user-images.githubusercontent.com/802457/70804366-26548180-1d6b-11ea-9eaa-ee22fa2d44bd.png)
