### ISSUE TITLE
5n1 Temperature

### ISSUE THREAD

**Issue by bbipro** [matthewwall/weewx-sdr#74]
I just rebuilt my system and when I fired it up I noticed all the Acurite5n1Packet messages now had a V2 on the end.  No big deal, added it.

But I wasn't getting any outdoor temperature.   For some reason my 5n1 puts out F and not C, but in the code there's no way to deal with F.   so it was never being output.  I just added an F line with no conversion and that seems to have fixed it.

Here's the json return I'm getting for what it's worth:

{"time" : "2020-02-05 02:20:54", "model" : "Acurite-5n1", "subtype" : 56, "id" : 956, "channel" : "A", "sequence_num" : 2, "battery_ok" : 1, "wind_avg_km_h" : 3.483, "temperature_F" : 31.300, "humidity" : 66}

Thanks again,

ig.

**Comment by matthewwall** [comment]
fixed at commit 414cee7
