### ISSUE TITLE
Ambient Weather F007TH Thermo-Hygrometer ident. change

### ISSUE THREAD

**Issue by Jocker666z** [matthewwall/weewx-sdr#76]
`IDENTIFIER = "Ambient Weather F007TH Thermo-Hygrometer"` become
`IDENTIFIER = "Ambientweather-F007TH"`

`out:[u'{"time" : "2020-02-05 19:33:11", "model" : "Ambientweather-F007TH", "id" : 201, "channel" : 5, "battery_ok" : 1, "temperature_F" : 39.400, "humidity" : 60, "mic" : "CRC"}\n']`

Sorry for miss close/open issue

**Comment by matthewwall** [comment]
applied at commit e355db6
